name: "AI Code Review Action"
description: "Perform code reviews and comment on diffs using OpenAI API (written in Go)."

inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: true
  OPENAI_API_KEY:
    description: "OpenAI API key for GPT."
    required: true
  LLM_MODEL_NAME:
    description: "OpenAI API model."
    required: false
  LLM_PROVIDER:
    description: "LLM provider to use."
    required: false
  exclude:
    description: "Glob patterns to exclude files from the diff analysis"
    required: false
    default: ""

runs:
  using: "docker"
  image: "Dockerfile" # This will build the Dockerfile in the same directory
  args:
    - ${{ inputs.GITHUB_TOKEN }}
    - ${{ inputs.OPENAI_API_KEY }}
    - ${{ inputs.LLM_MODEL_NAME }}
    - ${{ inputs.LLM_PROVIDER }}
    - ${{ inputs.exclude }}


