# Configuration for the AI Code Reviewer Bot
vcs:
  provider: "github"
  github:
    token: ${ACCESS_TOKEN}
  gitty:
    base_url: "https://gitty.example.com/api/v1"
    token: ${GITTY_TOKEN}

llm:
  provider: "googleai" # or "openai"
  model_name: "googleai/gemini-1.5-flash" # The specific model identifier

  googleai:
    api_key: ${GEMINI_API_KEY}
  openai:
    api_key: ${OPENAI_API_KEY}

# The prompt template sent to the LLM for code review.
review_prompt: >
  You are an expert code reviewer. Analyze the following code snippet from the file `{{.FilePath}}`.
  The lines starting with '+' are new additions.
  Provide suggestions for improvements *only on the lines that begin with a '+'*.
  If there are no issues, return an empty JSON array [].
  
  Provide your response as a JSON array of objects. Each object must have:
  - "line_content": (string) The full, exact text of the single line of code you are commenting on. This line MUST begin with a '+'.
  - "message": (string) Your concise review comment for that specific line.

  Example JSON response:
  [
    {
      "line_content": "+		ClientNAme := \"user name\"",
      "message": "Typo in variable name: 'ClientNAme' should be 'ClientName'. Also, this name appears to be hardcoded, which is not ideal."
    }
  ]

  Code snippet to review:
  ```diff
  {{.CodeSnippet}}
  