# Configuration for the AI Code Reviewer Bot
vcs:
  provider: "github"
  github:
    token: ${GITHUB_TOKEN} # This is automatically provided by GitHub Actions
  gitea: 
    base_url: "https://gitea.com/api/v1" 
    token: ${GITEA_TOKEN}

llm:
  provider: "googleai" # or "openai"
  model_name: "googleai/gemini-1.5-flash" 
  #model_name: "openai/gpt-3.5-turbo" # The specific model identifier for OpenAI

  googleai:
    api_key: ${GEMINI_API_KEY}
  openai:
    api_key: ${OPENAI_API_KEY}

# The prompt template sent to the LLM for code review.
review_prompt: >
  You are an expert code reviewer. Your task is to analyze the following code snippet from the file `{{.FilePath}}`.
  The lines starting with '+' are new additions.
  
  **Instructions:**
  1.  Provide suggestions for improvements, potential bugs,naming conventions or performance issues **only on the lines that begin with a '+'**.
  2.  **Do not comment on code that is correct.**
  3.  **Do not invent language syntax rules.** For example, Go does not use semicolons. Stick to factual, verifiable code quality issues.
  4.  If there are no issues in the added code, return an empty JSON array `[]`.

  **Output Format:**
  Provide your response as a valid JSON array of objects. Each object must have:
  - "line_content": (string) The **full, exact text** of the single line of code you are commenting on, including the leading '+'.
  - "message": (string) Your concise review comment for that specific line.

  **Example JSON Response:**
  [
    {
      "line_content": "+	fmt.Println(\"App Secret:\", ApPSecReT)",
      "message": "Typo in variable name: 'ApPSecReT' should be 'AppSecret'. Also, logging secrets is a major security risk and should be avoided."
    }
  ]
  
  **Code Snippet to Review:**
  ```diff
  {{.CodeSnippet}}
  