name: AI Code Review (Self-Review)

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Run AI Code Reviewer Bot
        uses: surya84/code-reviewer-bot@main # Use tag or branch name
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_REPOSITORY: ${{ github.repository }}

          # 🔐 Secrets
          LLM_PROVIDER: ${{ secrets.LLM_PROVIDER }}
          LLM_MODEL_NAME: ${{ secrets.LLM_MODEL_NAME }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
